### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by sesipod** [tmunsch/Pterodactyl-Wordpress#1]
Have you made any more progress with this? It would be super super awesome to have WordPress as an egg in Pterodactyl and I think I speak for a large number of people :) 👍

**Comment by TwixGamer00** [comment]
Yep i also hope so

**Comment by tmunsch** [comment]
Yes I can upload my changes later today

**Comment by sesipod** [comment]
Hello just checking in (:

**Comment by tmunsch** [comment]
Sorry been slammed today I will work on this the upcoming week. Keep in mind you will need a reverse proxy for it to open via a domain

**Comment by sesipod** [comment]
Yeah awesomeness thanks ! 
reverse proxy is not a problem already have that going 😬

**Comment by sesipod** [comment]
update :)

**Comment by tmunsch** [comment]
Added Egg, Enjoy
https://github.com/tmunsch/Pterodactyl-Wordpress/commit/3980c84f6f8c8c8104a1444ca3f5db891650c17a

**Comment by NoodlesDev987** [comment]
Will you make reverse proxy guide?
