### ISSUE TITLE
denied: access forbidden

### ISSUE THREAD

**Issue by RustinCassiem** [tmunsch/Pterodactyl-Wordpress#3]
container@pterodactyl~ Error Event [4dec4ea2-1a81-46da-9a6f-954372601da7]: environment/docker: failed to pull "registry.gitlab.com/tmunsch/pterodactyl-wordpress" image for server: Error response from daemon: Head https://registry.gitlab.com/v2/tmunsch/pterodactyl-wordpress/manifests/latest: denied: access forbidden

**Comment by tmunsch** [comment]
Sorry but someone has stolen my code and is selling it for a profit so I am removing this egg.

**Comment by ok236449** [comment]
Hi, can you please get the repository back up on gitlab? I was using your egg and now I can´t start it because of it. Or can you hand me just the files so I can pull it locally?

**Comment by RehanPlayz** [comment]
> Hi, can you please get the repository back up on gitlab? I was using your egg and now I can´t start it because of it. Or can you hand me just the files so I can pull it locally?

Ye me too

**Comment by tmunsch** [comment]
It's back up, try now

**Comment by ok236449** [comment]
Thank you very much. It works

**Comment by RehanPlayz** [comment]
> It's back up, try now

Thanks 👍

**Comment by RehanPlayz** [comment]
> Sorry but someone has stolen my code and is selling it for a profit so I am removing this egg.

BTW who stole it and selling it so we can report it or something

**Comment by tmunsch** [comment]
https://pterodactylmarket.com/resource/246

I purchased it and it's identical to mine line for line.

**Comment by RehanPlayz** [comment]
> https://pterodactylmarket.com/resource/246
> 
> I purchased it and it's identical to mine line for line.

Oh ok

**Comment by ok236449** [comment]
I really don't like this kind of people. Trying to make money on work of others. We shall somehow stop it by reporting them. They can't make money on open source project!

**Comment by RehanPlayz** [comment]
> I really don't like this kind of people. Trying to make money on work of others. We shall somehow stop it by reporting them. They can't make money on open source project!

Ye I'm going to try an report it

**Comment by ok236449** [comment]
I haven't found any report button nor contact to a manager :( If you find a way to report, post it here. The more people the better...

**Comment by RehanPlayz** [comment]
> I haven't found any report button nor contact to a manager :( If you find a way to report, post it here. The more people the better...

Try an reporting it on Pterodactyl discord

**Comment by ok236449** [comment]
It is not an official pterodactyl egg

**Comment by RehanPlayz** [comment]
> It is not an official pterodactyl egg

Oh ye forgot

**Comment by ok236449** [comment]
> It is not an official pterodactyl egg

Still a great egg tho... I don't know why don't they want to support such eggs. Like web, vps,...

**Comment by RehanPlayz** [comment]
> > It is not an official pterodactyl egg
> 
> Still a great egg tho... I don't know why don't they want to support such eggs. Like web, vps,...

They say that Ptero isn't meant for that and use something like Cpanel

**Comment by ok236449** [comment]
I know, but 1. cpanel is paid, 2. Having 2 independent panels isn't really a convenient way...

**Comment by RehanPlayz** [comment]
> I know, but 1. cpanel is paid, 2. Having 2 independent panels isn't really convenient...
1. There are a couple free alternatives but I don't think they are very good
2. Ye true

**Comment by tmunsch** [comment]
Pterodactyl is a game agnostic panel. Which it does very well. After some time people realize it's true potential but it isn't within the scope of the project. We are already battling so many support requests that it wouldn't make sense for them to widen the burden.
